<a href="https://colab.research.google.com/github/thanugeorge13/ML/blob/main/MLLab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://media.geeksforgeeks.org/wp-content/uploads/20240319120216/housing.csv

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('housing.csv')

In [3]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [8]:
import matplotlib.pyplot as plt
#import seaborn as sns

data.hist(bins=50, figsize=(20,15)) # Plot histograms for all numerical features
plt.suptitle('Histograms of All Numerical Features')
plt.show()

In [7]:
from sklearn.model_selection import train_test_split

train_set_random, test_set_random = train_test_split(data, test_size=0.2, random_state=42)

print(f"Random Split - Training set size: {len(train_set_random)} records")
print(f"Random Split - Test set size: {len(test_set_random)} records")

Random Split - Training set size: 16512 records
Random Split - Test set size: 4128 records


In [16]:
import matplotlib.pyplot as plt

# Visualize Geographical Data with Housing Prices
plt.figure(figsize=(10, 7))

# Scatter plot of longitude vs latitude, colored by median_house_value
plt.scatter(data['longitude'], data['latitude'],
            alpha=0.4,
            c=data['median_house_value'],
            cmap='jet',
            s=data['population']/100) # Use population for size, scaled down for better visualization

plt.colorbar(label='Median House Value')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Housing Prices based on Geographical Location')
plt.grid(True)
plt.show()

### What the graph indicates with respect to housing prices and location:

This scatter plot visualizes the geographical distribution of housing prices, with:

*   **X-axis:** Longitude (west-east position)
*   **Y-axis:** Latitude (south-north position)
*   **Color:** Represents the `median_house_value`, with warmer colors (yellow, red) indicating higher prices and cooler colors (blue, green) indicating lower prices.
*   **Size:** The size of each circle is proportional to the `population` of that district, giving an idea of population density in higher/lower price areas.

From the graph, we can observe several key patterns:

1.  **Coastal vs. Inland:** There's a clear trend of **higher housing prices along the coast**, particularly in Southern California (lower latitude, around -118 to -120 longitude, where you see more yellow/red dots). As you move further inland, prices tend to decrease, becoming predominantly cooler colors.
2.  **Major Urban Centers:** Hotspots of high housing values (bright yellow/red areas) appear to correspond to major metropolitan areas, such as the **San Francisco Bay Area** (around latitude 38, longitude -122) and the **Los Angeles area** (around latitude 34, longitude -118). These areas often have higher job opportunities, amenities, and desirability.
3.  **Population Density:** Larger circles (representing higher populations) often coincide with these high-value coastal and urban areas, suggesting a correlation between population density, urbanization, and increased housing demand/prices.
4.  **Regional Differences:** While coastal areas are generally more expensive, there are variations. Southern coastal regions seem to have some of the highest values, possibly due to weather, beaches, and economic hubs.

In summary, the graph strongly indicates that **geographical location, especially proximity to the coast and major urban centers, is a primary driver of housing prices** in California, with areas closer to the ocean and densely populated cities commanding higher median house values.